### ISSUE TITLE
Windows version no audio (Shadowcast 2)

### ISSUE THREAD

**Issue by Invius** [nicokimmel/genkiarcade-electron#2]
I've built the windows version, and x64 is not outputing any audio. Input latency is incredebly low in this app, I'm very impressed, comparing it to the genki arcade v1.6, its leagues ahead.

**Comment by nicokimmel** [comment]
I cant really reproduce the issue as I dont have a windows installation currently. Maybe in the near future but I cant guarantee it - sorry.

**Comment by nicokimmel** [comment]
@Invius Good news, this should now be fixed with Commit [cc426d2462ebb1d76c7b67b5eb092f72d7e4415d](https://github.com/nicokimmel/shadowcast-electron/commit/cc426d2462ebb1d76c7b67b5eb092f72d7e4415d). On Linux the ShadowCast sound devices all started with "ShadowCast" so I assumed it would be the same on Windows. Apparently I was wrong. So now it checks if contains the string.
